services:
  mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password # si este comando falla, tal vez haga falta actualizar mysql en tu equipo
    # Mecanismo de autenticación nativo de mysql
    ports:
      - 3310:3306 # Puerto cambiado de 3310 a 3308 para evitar conflictos
    environment: # variables de entorno
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: empresa
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes:
      - mysql_crud_data:/var/lib/mysql # Persistencia de datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    environment:
        PMA_HOST: mysql

    depends_on:
      - mysql

volumes:
  mysql_crud_data:
